### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ScaryWhiteGuy** [blaxxun-boop/DualWield#1]
Good evening, i was trying to set this up however its not working, i downloaded the required compatible mod, might be because i have other mods installed, i use vortex for all my other mods and those are still running, any tips or suggestions on how to get this to run with the vortex mods

**Comment by AzumattDev** [comment]
This mod doesn't have any requirements. Also, the re-upload to nexus is not permitted. You should remove that.

**Comment by blaxxun-boop** [comment]
@ScaryWhiteGuy What exactly makes you think it doesn't work?
Please note that you can only dual wield weapons of the same type, e.g. two swords or two maces, but you cannot dual wield a sword with a mace.

And yes, please note that it's not allowed to redistribute mods of other people. I especially do not wish for my mods to be on Nexusmods, because they claim full ownership of every file uploaded there.
