### ISSUE TITLE
Please enable EpicLoot?

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/DualWield#11]
Please consider re-enabling compatibility with EpicLoot?  Or at least making it an option?  Many people love both mods and would love to run both.  They work fine together, even +damage on both weapons.  Thank you!

**Comment by blaxxun-boop** [comment]
Did the bug in Epic Loot get fixed?
More mods to follow with incompatibilities with Epic Loot soonish. Might as well make the switch from Epic Loot now.

**Comment by Oosquai** [comment]
It did.  I'm playing currently with the latest Epic Loot and your previous version of Dual Wield.  I have pairs of weapons with +damage of various types in either hand, and they interact correctly when dual wielded.  They do not get multiplied.  It works great, and your dual wield mod is amazing.  Please?

**Comment by Shamelesstimmy** [comment]
he has no intention of making it compatible, he just wants to push his jewellery crafting mod.

epic loot has more mods becoming compatible with it and it has updates plus future plans to include more stats.

**Comment by Oosquai** [comment]
It's a shame.  blaxxun-boop makes great mods, but he's severely limiting his own audience by making them incompatible with such a widely used mod.

**Comment by Shamelesstimmy** [comment]
yes it is a shame, although ive been able to find the code line that doesnt allow epic loot to work with the mod so ill have no problem using the current update

**Comment by blaxxun-boop** [comment]
Or, and this might be a crazy idea, there is a bug in Epic Loot that multiplies your enchantments on your weapons, if you dual wield.
As in, if you equip two knives with +50 additional fire damage (which is insane already, because it's twice the damage that end game knives deal in vanilla), it first of all stacks them, for a whopping 100 additional damage per hit and secondly, applies the damage twice while dual wielding, because dual wielding splits up your damage into a right hand and a left hand hit, which makes you end up dealing north of 200 damage more per hit in a chain attack. If you have used dual wield, you know that knives have very low damage for the first two hits, like 5-10 damage. Epic Loot turns this into 205-210 damage per hit.

And maybe, just maybe, there were quite a few server admins that complained about their users abusing this and asked _me_ to fix this. Which I would be more than happy to do, if it was a bug in Dual Wield or even in Epic Loot, where I have contributed _a lot_ in the past, which you would know, [if you follow what I do](https://github.com/RandyKnapp/ValheimMods/pulls?q=is%3Apr+author%3Ablaxxun-boop+is%3Aclosed+), if Epic Loot would still be maintained and fixing this issue wouldn't require a complete rewrite from scratch when it comes to how Epic Loot calculates its enchantments.
And maybe, I got eventually tired of being asked to fix this, so I decided to add the incompatibility, until Epic Loot is fixed (which is probably never, but who knows).

**Comment by Shamelesstimmy** [comment]
> Or, and this might be a crazy idea, there is a bug in Epic Loot that multiplies your enchantments on your weapons,

ive been playing with epic loot and dual wield an none of that has been happening, still takes the same amount of damage to kill a base level greybrute. it seems the bug was fixed.
also recently added the creature level control to make it more fun which added a danger factor to the game.
i do follow lot of these mods an have even gone as far as getting into the code an doing somethings for myself to see what different things can happen like being able to equip a sword an axe or different combos an making it so two handed can be equip with a shield (with the factor of two handed get a damage reduction when equip one handed)
alot of the time coders need alot of different people trying different things to see what can be fixed.

i still enjoy alot of your mods as it has improved alot of an my friends games, ill even be happy to send you the files with my changes so you can have a look yourself an see if theres anything your wanted to adapt

**Comment by Shamelesstimmy** [comment]
wouldnt be a bad idea to add a version of dual wield that works with epic loot but so suggest the add creature level control to increase the difficulty or just place a warning on the page that states it will make charcters OP

**Comment by blaxxun-boop** [comment]
Creature Level and Loot Control will be incompatible with Epic Loot, starting with Mistlands.
So, no, not a good idea. If you want a really good idea: Switch to Jewelcrafting.

**Comment by Shamelesstimmy** [comment]
yeah ive noticed your trying to lock out epic loot from being used with any of your mods to boost jewelcrafting unfortunately jewelcrafting is a horrible mod. we started with using that before epic loot an in the end drop it as we would have to basically start over with gear coz we could never socket anything due to it always getting destroyed. could bearly get enough gems together coz they would constantly get destroyed, there was no fun in having to go back out an farm trolls to make new gear just to move onto the next area. epic loot allows more fun with the loot drop as we were able to have fun an progress at a reasonable rate without the fear of it being destroyed.
so no we wont be switching to jewelcrafting and it sounds like another mod ill have to recode to enjoy but thanks for the heads up.
good for you though, great way to loose mod users by not allowing other to play the way they want

**Comment by blaxxun-boop** [comment]
Oh, my sweet summer child.

There are a lot of bug fixes for other mods in CLLC. I started doing this, because people kept reporting their errors to me, saying it's CLLCs fault, even though it clearly isn't. We are currently at the point, where some mods won't even startup properly, if CLLC isn't installed (which is mostly due to a bug in Valheim itself, where some items do not record their drop prefab properly. CLLC fixes that for every mod, but it's still something that the other mods should be aware of and work around it, rather than relying on CLLC to fix it for them).

This makes the code way more complicated than it needs to be. So, I will simply stop doing that and remove the bug fixes for other mods from CLLC. These issues should have been fixed in the mod causing them a long time ago, but they weren't. You are more than welcome to add your bug reports to the other 500 ignored bugs in Epic Loot and stop bothering me with issues I am not responsible for whatsoever.

I kept doing this until now, because I knew that people like their Epic Loot and there wasn't any alternative. I've announced that I will stop being Epic Loots necromancer months ago, to give people time to find other solutions or voice their feature requests for Jewelcrafting.
Still, you are welcome that I kept Epic Loot alive for this long. Maybe just stop trash talking, if you have no freaking idea what is going on.

Other than that, it's not Jewelcraftings fault that you are unable to configure a mod. All of my mods are flexible as hell and every single "issue" you've mentioned has a config option.
