### ISSUE TITLE
Questions about Dual Wield / Epic Loot bug

### ISSUE THREAD

**Issue by Malus565** [blaxxun-boop/DualWield#13]
Hello, a couple questions.  Have you looked at Epic Loots recent update to see if the bug is still there??  

Also if it is still there, what is the bug? Perhaps you or someone else can report it to him to fix.

**Comment by blaxxun-boop** [comment]
Epic Loot multiplies the effect of enchantments on weapons by 4, if you dual wield, because it applies the enchantment of every equipment item on each hit, instead of just applying the enchants on the weapon that dealt the hit.

And no, Epic Loot is pretty much abandonded and I doubt that this will ever get fixed. The latest "updates" were just adding more and more life support to it, sometimes by removing broken features of the mod, instead of fixing them.

Switch to Jewelcrafting and you won't have any issues.

**Comment by Malus565** [comment]
ah ok, thanks for the information, much appreciated.
