### ISSUE TITLE
Dual Wield and Epic Loot mod

### ISSUE THREAD

**Issue by Nystrom91** [blaxxun-boop/DualWield#16]
First of all i'd like to say before the big updates when DualWield was compatible with Epic Loot they worked perfectly fine together and it was alot of fun.

I don't think you should decide for other players they can't enjoy a mod because you think its cheaty.
Epic loot had in fact been updated and maintained these past weeks. And has caused no issues for me or the players on my server.
Jewel crafting looks nice but it just is not really what people are looking for, i'd guess thats why in most modpacks you will find the epic loot mod instead of your jewel crafting mod. 

So please reconsider making it compatible again with other mods like the epic loot mod.

**Comment by blaxxun-boop** [comment]
Nope.

And Dual Wield never worked "perfectly fine" with Epic Loot. The issues existed since the release of Dual Wield. More and more server owners complained about it to me, because people were abusing Dual Wield in combination with Epic Loot damage added enchantments on their server and I got tired of getting blamed for bugs in Epic Loot, so I added the incompatibilitiy, which will stay until the bugs in Epic Loot are fixed.
