### ISSUE TITLE
Sheath/Unsheath swaps weapons

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/DualWield#9]
In some cases it matters which weapon is in which hand (when using Epic Loot).  Unfortunately, sheathing and then unsheathing weapons (with R key) causes the right and left hand weapons to swap.  Any way to fix please?

**Comment by blaxxun-boop** [comment]
This actually reminds me that I still have to make Dual Wield incompatible with Epic Loot.
Please don't use Dual Wield with Epic Loot. The way Epic Loot calculates your enchantments is stupid and cannot handle players having two one-handed weapons equipped properly. For example, if you enchant +50 fire damage on your weapons (which is ridiculous already), you will actually deal +200 fire damage with each attack, because it keeps multiplying the enchantments on your weapons.

I'd recommend switching to Jewelcrafting, instead of Epic Loot, but I might be biased. 😉

**Comment by Oosquai** [comment]
haha, biased indeed!  All good - Jewelcrafting looks awesome!  I love the concept of farming for and combining gems for synergistic effects.

Anyway, I have not found what you're saying to be true.  I'm testing it right now, in fact, and I'm finding that EL and DW behave the way I'd expect.  If I have 5 fire damage on my mainhand dagger and 5 on my offhand, I get dots calculated from 10 fire damage when I hit things while DW or 5 when just using one of them.  I'm using the latest versions of EL and DW.  Hope this helps!
Please don't break how nicely they play together.  They're great!

But...  if you could make it so sheathing and unsheathing don't swap hands, that would be amazing!

And...  if you could add a config file parameter to allow me to prevent DW by item name, like (excludedualwieldnames: "rune of firebolt", "rune of frostbolt") that would be awesome!

Love your mods!  Thank you so much!

**Comment by blaxxun-boop** [comment]
Fixed in the recent update.
